title: Avula Maheswar Reddy's Cybersecurity Portfolio
description: Everything is binary at the end, if it is binary then it is not the end.
show_downloads: true
google_analytics:  # Add your Google Analytics tracking ID if needed

theme: jekyll-theme-hacker

# Add this plugin if needed
plugins:
  - jekyll-include-cache

# Custom CSS
# This is where you link your custom CSS file
include: 
  - assets/css/style.css
